version: '3'

services: 
  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/docker-node-mongo
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/srv/app/keeno-server
    links:
      - mongo
    command: yarn start
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ./
    environment:
      - CONTAINER_NAME=server
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./:/srv/app/keeno-client
    links:
      - server
    command: yarn client