version: 3

services:
  server: 
    build: ./server
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    voluems:
      - ./server:/srv/app/keeno-server
    command: yarn start
  client:
    build: ./
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    voluems:
      - ./:/srv/app/keeno-client
    links:
      - server
    command: yarn start
    