export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';

export const SET_MOVIES = 'SET_MOVIES';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const SET_ERROR = 'SET_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const TOGGLE_FAVOURITE = 'TOGGLE_FAVOURITE';
